### PR TITLE
Allow modification of enableConnectionRSSIMeasurement and fixed typos with the word Sampling

### PR DESCRIPTION
**Pull request by ihassin**
Allow modification of enableConnectionRSSIMeasurement and fixed typos with the word Sampling

### CODE REVIEW

**Comment by mariusheil** [comment]
Thanks. Just a quick question, why did you remove the const keyword? I've used const because currently it's not meant to be changed at rumtime (you may of course change it at compile time). Changing the value at runtime would not do anything as we need to explicitely enable radio notifications by calling a function.

**Comment by ihassin** [comment]
Hi Maruis - I was not aware that a function call is needed. I can wrap this flag in a public method in the base class and call that function, allowing modules to turn RSSI measurements on or off during runtime, or else, quick and dirty, put the 'const' back.

Which do you prefer?

**Comment by mariusheil** [comment]
I've still got a mesh configuration module on my backlog that will handle this, so for now, I'd suggest to make it a const again and I'll fix this when I start working on the other module.

**Comment by ihassin** [comment]
ok man, will do.

**Comment by ihassin** [comment]
Hi @mariusheil , will you be pulling this in?

**Comment by mariusheil** [comment]
yes, of course :-) sorry for the delay

**Comment by ihassin** [comment]
Cool thanks! It will allow me to propose to add the RSSIModule to the examples directory

**Pull request merged**
