### PR TITLE
adds makefile from compile.sh script (working on debug version for gcc)

### PR DESCRIPTION
**Pull request by tkadom**
Added a makefile for gcc under osx.  

removes copy of external source files.
creates _build directory with all the object files
prepares for gcc debug

### CODE REVIEW

**Comment by WindohsCrasher** [comment]
Hi,

thanks for your awesome work :) I just tested the script on Linux and had the following two issues:

-The makefile searches for the ARM GCC/G++ in $GNU_INSTALL_ROOT which is /usr/local, but the compiler comes with the FruityMesh development environment in $HOME/sdk/. Could you please adjust the path and (if possible) device between OSX/Linux platform for choosing the correct compiler?
-In line 177, the library include path is "$(EHAL_PATH)/ARM/Nordic/nRF51/CMSIS/DEBUG", however, the directory's actual name is "Debug". Since Linux file systems work case sensitive, it doesn't find the folder

After adjusting these two things, the makefile works flawlessly - thanks again! :)

**Comment by tkadom** [comment]
Good catch on linux build.  weird that it is actually working under osx?  I
went ahead and committed and pushed that change and identified the
directory properly as "Debug"

The reason I went with GNU_INSTALL_ROOT over the local install of armgcc
toolchain is primarily because the SDK from nordic uses that convention in
their makefile here

(Nordic SDK install dir)/components/toolchain/gcc/Makefile.posix)

and I wanted to remain consistent for Nordic SDK gcc developers who have
already installed the arm gcc/g++ toolchain.  In my case it was under
/usr/local/gnu

The makefile actually creates all the associated objects under _build, to
simplify debugging so ultimately this could simplify your project hierarchy
for gcc.  you could just have the fruitymesh project and deprecate devenv
once fruitymesh has enough configuration support to stand on its own.

I am not sure which approach is better.  It certainly would not hurt to
default the GNU_INSTALL_ROOT to the nrf/sdk directory for people who have
not already set up their Nordic SDK.  There is also a good enough reason to
have a separate local copy of the nordic SDK under your project hierarchy
because you do ask for the header file change in the S130 softdevice.
 (Crazy cool that you were able to find that issue, I can not imagine how
much debugging that must have taken!).  Has Nordic accepted that change, or
is that only valid for FruityMesh?  if it is a local change that Nordic is
not going to include, then we should continue to keep the local copy of
nordic SDK.  Otherwise it would be ideal if fruitymesh could support the
setup described in the wiki, and with minimal change support users who
already have those software dependencies installed elsewhere

We were also thinking of including an ansible script to build a linux VM
from scratch for the nordic environment as well.  Itamar is working on that
now for our workshop.  Perhaps also a configuration script for osx to pull
down all the pre-requisites.

Ultimately it would be great if ARM developers who might already have the
SDK dependencies installed on their system would not need to re-install
them again for fruitymesh.  That was the logic behind leveraging how the
Nordic SDK deals with GNU  INSTALL ROOT.

Thoughts?

Tim

**Comment by mariusheil** [comment]
Hi,

thanks a lot for that makefile. I am currently still using the managed make that eclipse provides because it makes managing different build configurations a lot easier. I'll have to do some reading on makefiles to see how I'd manage a workflow with these. Currently, the live error checking is in sync with the build process and allows me to change between different configurations for nRF51, nRF52 e.g.
But I'm very interested in  different workflows. I hope its possible to find a setup that works flawlessly and for every OS. Maybe I can use a Mac in the next days and set everything up.
Do you use an IDE or an editor for work?
I didn't actually find that change in the SDK myself but copied it from someone else when I set everything up, but the compiler will point you in the right direction if you forget to change the file ;-) (Happened to me from time to time)
I've opened a question on devzone to ask for a change.

What should I write in the Wiki to explain the process?

**Comment by tkadom** [comment]
Happy to help.  I do not use eclipse.  I am still a bit old school that way.  It is a great IDE, but I kind of prefer being a bit closer to the code environment.

On OSX brew install is what most will use to install the ARM toolchain.  So there will be a few differences.  Setting up the SDK and running their examples is where I started.  Fairly simple.  

Hey Marius, have you ever stress tested your mesh?  Do you know hoe many concurrent nodes and clusters you could support?

- Tim

**Comment by mariusheil** [comment]
Hi,

aside from the simulation that you'll find in the repository, I haven't had
the chance to stress test it just yet. The mesh should support around
20.000 nodes (just by the id numbers), because it has no memory overhead
for nodes. But as soon as the network grows, there will be a lot more
traffic. I haven't had the time to implement some basic quality of service
right now, which means that messages will get dropped if the message buffer
of a node is filled. Because there's not much error checking on the
messages, the clusterSize will sometimes be wrong on individual nodes. That
should not hurt too much, though, because it does not need be be exact.
(Should be fixed nevertheless ;-))
If the network grows too big, there will be a lot of join messages, which
means that it will probably take a long time until the network is built. In
the next step, I need to group the JOIN_ME messages, so that they
accumulate some updates, before sending them. This way, we should be able
to fix the bandwidth problem during the network setup.
As for clusters: Only one cluster should exist in a connected network at a
time. Two different networks are currently not designed to connect to each
other.
Over the weekend I've had 17 nodes connected throughout the building and 4
of them failed. I think they got stuck in my error handler. I have to find
the reason and solve it. I haven't implemented any watchdog yet and if a
node fails, it will be stuck in an endless loop.

Regards,
Marius

2015-09-19 4:29 GMT+02:00 Tim Kadom <notifications@github.com>:

**Comment by tkadom** [comment]
Thanks Marius,

We will likely be trying around Wo this week and so hopefully there will be a few more folks debugging :). 

Do you have any architecture write ups or white papers around fruity mesh that can help explain the algorithm to others?

Tim

**Comment by mariusheil** [comment]
Hi,

sorry for the late response. There is not much material that I can publish just yet, but there is a lot that I have available. I want to do a bigger write up on the algorithm and go into more detail with the information. Maybe you could give me some key points of what topics you are particularly interested in, so that I can put more focus there.
How fast would you need that information? I am on vacation for about 10 days beginning on Friday, so i do not have much time until then. If you don't need the information for the next two weeks, I could certainly put something together. if you need it faster, I'll have to do a quick n' dirty copy and paste job ;-)

Marius

**Comment by tkadom** [comment]
Would be helpful for tutorial workshop.  So even high level description beyond what is in wiki would be good.  Workshop is in two weeks. Trying to pull a lesson together next week when I have free time.  It's informal, so not that critical, but it would be nice to have more detail...

Tim Kadom




On Wed, Sep 23, 2015 at 8:46 AM -0700, "Marius Heil" <notifications@github.com> wrote:












Hi,



sorry for the late response. There is not much material that I can publish just yet, but there is a lot that I have available. I want to do a bigger write up on the algorithm and go into more detail with the information. Maybe you could give me some key points of what topics you are particularly interested in, so that I can put more focus there.

How fast would you need that information? I am on vacation for about 10 days beginning on Friday, so i do not have much time until then. If you don't need the information for the next two weeks, I could certainly put something together. if you need it faster, I'll have to do a quick n' dirty copy and paste job ;-)



Marius

**Comment by mariusheil** [comment]
Alright, got something for you ;-) I've created a wiki page entry here: https://github.com/mwaylabs/fruitymesh/wiki/The-Algorithm-in-Detail
I haven't yet linked it to the main page because I want to correct some of the stuff, but i guess you could gather quite a lot from it. I'll be back after my holidays.

**Comment by tkadom** [comment]
Thanks Marius!

Tim Kadom




On Thu, Sep 24, 2015 at 6:40 AM -0700, "Marius Heil" <notifications@github.com> wrote:












Alright, got something for you ;-) I've created a wiki page entry here: https://github.com/mwaylabs/fruitymesh/wiki/The-Algorithm-in-Detail

I haven't yet linked it to the main page because I want to correct some of the stuff, but i guess you could gather quite a lot from it. I'll be back after my holidays.

**Comment by tkadom** [comment]
Hi Marius,

Thanks so much for the writeup.  One of my co-workers is working on a
gateway to serialize and de-serialize the messages from the mesh so we can
create a node that relays messages out and in from a node red server.  I am
creating another experimental module for triggering a neopixel display over
fruitymesh using GPIO.  That is likely something we will build our tutorial
workshop around.  it will be simple extension of the ping module.

I wanted to simply plug a fruitymesh usb dongle into a usb battery, but
fruity is not too happy about not having a connection present and seems to
continually reset itself when it is connected to a usb battery.  Not sure
if that is a configuration setting somewhere that i missed in the wiki...

Nordic is in town in two weeks (Atlanta), and our workshop will be done by
then.  I will attend their one day event, and give your fruitymesh a bit of
publicity ;)

**Comment by mariusheil** [comment]
Hi,


I have very limited internet here and no computer to recreate the problem, sorry. But i am using the mesh with usb plugs all the time without any problems. Did you test if the precompiled version resets itself? One more thing you could try is to disable the logger and the terminal in the config. 






Gesendet von Windows Mail





Von: Tim Kadom
Gesendet: ‎Montag‎, ‎28‎. ‎September‎ ‎2015 ‎05‎:‎08
An: mwaylabs/fruitymesh
Cc: Marius Heil




Hi Marius,

Thanks so much for the writeup. One of my co-workers is working on a
gateway to serialize and de-serialize the messages from the mesh so we can
create a node that relays messages out and in from a node red server. I am
creating another experimental module for triggering a neopixel display over
fruitymesh using GPIO. That is likely something we will build our tutorial
workshop around. it will be simple extension of the ping module.

I wanted to simply plug a fruitymesh usb dongle into a usb battery, but
fruity is not too happy about not having a connection present and seems to
continually reset itself when it is connected to a usb battery. Not sure
if that is a configuration setting somewhere that i missed in the wiki...

Nordic is in town in two weeks (Atlanta), and our workshop will be done by
then. I will attend their one day event, and give your fruitymesh a bit of
publicity ;)

**Comment by tkadom** [comment]
Hi,
I did try to disable the terminal, but the symptoms are that the board flashes the normally steady green led rapidly when I put it on a battery.  It will come up and even connect, but then will reset itself after a few seconds.  And come up again and continue that behavior.  
As soon as I plug into the USB battery the rapidly flashing green LED happens.  The same code works fine when it is connected to my laptop.  I disabled terminal in the header and reloaded the code but the behavior was the same.  I am pretty sure I disabled logger at the same time.  Will try the precompiled binary to see if maybe there is something else.  If not I will try to trace the code.  Thought maybe it was something familiar.  Also the sample ping code from your example source folder yields a command not found error.  I followed all the steps on the wiki, so I am not sure why that is happening yet.  I do see the ping module listed, so I know the hex is loading...
Tim Kadom




On Mon, Sep 28, 2015 at 5:28 AM -0700, "Marius Heil" <notifications@github.com> wrote:










Hi,








I have very limited internet here and no computer to recreate the problem, sorry. But i am using the mesh with usb plugs all the time without any problems. Did you test if the precompiled version resets itself? One more thing you could try is to disable the logger and the terminal in the config. 




















Gesendet von Windows Mail

















Von: Tim Kadom


Gesendet: ‎Montag‎, ‎28‎. ‎September‎ ‎2015 ‎05‎:‎08


An: mwaylabs/fruitymesh


Cc: Marius Heil














Hi Marius,





Thanks so much for the writeup. One of my co-workers is working on a


gateway to serialize and de-serialize the messages from the mesh so we can


create a node that relays messages out and in from a node red server. I am


creating another experimental module for triggering a neopixel display over


fruitymesh using GPIO. That is likely something we will build our tutorial


workshop around. it will be simple extension of the ping module.





I wanted to simply plug a fruitymesh usb dongle into a usb battery, but


fruity is not too happy about not having a connection present and seems to


continually reset itself when it is connected to a usb battery. Not sure


if that is a configuration setting somewhere that i missed in the wiki...





Nordic is in town in two weeks (Atlanta), and our workshop will be done by


then. I will attend their one day event, and give your fruitymesh a bit of


publicity ;)





On Thu, Sep 24, 2015 at 9:40 AM, Marius Heil <notifications@github.com>


wrote:

**Pull request merged**
