### PR TITLE
Added flash instructions for Mac users along with a parameter file to…

### PR DESCRIPTION
**Pull request by ihassin**
… use with JLinkExe command-line utility

This is documentation and config file for command-line Mac OS X using JLinkExe.

### CODE REVIEW

**Comment by mariusheil** [comment]
Hi,
I've added your instructions to the wiki and I tried to cherry pick your pull request, but was not successful, so I've commited the deploy script in your name instead. I hope that's ok?
I guess that your deploy script does only flash the application and not the softdevice, so I've added another jlink script to flash the softdevice. Does that work for you? Could you test it for me because I do not have OSX.

Thanks

**Comment by ihassin** [comment]
Hi Marius - thanks for merging this. I've tested it and it works. I'll issue a new pull request to correct the "notice to mac users" file.

**Comment by mariusheil** [comment]
Hi,

i've updated the guide in the wiki unser Quick Start and put your instructions there.

Sent from my Windows Phone.

----- Ursprüngliche Nachricht -----
Von: "Itamar Hassin" <notifications@github.com>
Gesendet: ‎03.‎09.‎2015 12:58
An: "mwaylabs/fruitymesh" <fruitymesh@noreply.github.com>
Cc: "Marius Heil" <mariusheil@gmail.com>
Betreff: Re: [fruitymesh] Added flash instructions for Mac users along with a parameter file to… (#13)

Hi Marius - thanks for merging this. I've tested it and it works. I'll issue a new pull request to correct the "notice to mac users" file.

**Comment by ihassin** [comment]
Thank you.

- Itamar

**Comment by ihassin** [comment]
Just to be precise, 

jlinkexe deploy/upload_softdevice.jlink
jlinkexe deploy/upload_fruitymesh.jlink
should be 
jlinkexe upload_softdevice.jlink
jlinkexe upload_fruitymesh.jlink

Since you’re already in the deploy directory. :)

- Itamar

**Comment by mariusheil** [comment]
Updated, thanks :-)

2015-09-03 13:27 GMT+02:00 Itamar Hassin <notifications@github.com>:

> Just to be precise,
>
> jlinkexe deploy/upload_softdevice.jlink
> jlinkexe deploy/upload_fruitymesh.jlink
> should be
> jlinkexe upload_softdevice.jlink
> jlinkexe upload_fruitymesh.jlink
>
> Since you’re already in the deploy directory. :)
>
> - Itamar
>
>
>
>
>
>
>

**Pull request closed without merging**
