### PR TITLE
Added button state to button handler

### PR DESCRIPTION
**Pull request by NilsMinor**
I added an ButtonState enum to <types.h> with the states INITAL, PRESSED, RELEASED.  I also added a new variable 'ButtonState button1State' to <GlobalState.h>. The button handler will be called on falling and rising edge and still stores the hold time  in button1HoldTimeDs. Inside the overwritten Module::ButtonHandler function the user can use the new parameter 'ButtonState buttonState' to check whether it is a pressed or released event. #123

### CODE REVIEW

**Comment by mariusheil** [comment]
Hi,

that looks perfect, thanks. There is one thing however. My boss mentioned to me, that because we are GPL based, we need to make sure that all contributions can be used under GPL. He told me that he will follow up with you on how this is done.

Marius

**Comment by NilsMinor** [comment]
Hi Marius,

sounds good :) I never really contributed to other projects so let me know if you boss has any issues with my PR or with the license. My code would of course not change your GPL license.

Nils

**Comment by viveknath93** [comment]
Hi, 
I have a doubt!
I am new to this open-source development. As per my understanding, you are using the button for unenrolling the beacons by sending unenrollment packets to other nodes.
I need to use the button for different functionality - For Enrolling as well as Unenrolling / To trigger some messages to another node.

What if the existing development is conflicting than that I need?
Should I create local copies and use

**Comment by mariusheil** [comment]
Hi, the ButtonHandler is only implemented in the different Vendor modules with some functionality, so you will only have access to your own implementation. Whenever we used the button for some functionality in the open source modules, we also added a configuration variable to activate or deactivate this behaviour. You can simply disable this behaviour in your own featureset by activating what you want and disabling what you do not want.
We also use the button for different functionality for different featuresets that we develop.

**Comment by viveknath93** [comment]
> Hi, the ButtonHandler is only implemented in the different Vendor modules with some functionality, so you will only have access to your own implementation. Whenever we used the button for some functionality in the open source modules, we also added a configuration variable to activate or deactivate this behaviour. You can simply disable this behaviour in your own featureset by activating what you want and disabling what you do not want.
> We also use the button for different functionality for different featuresets that we develop.

Thank you for the information.

**Pull request closed without merging**
