### PR TITLE
Rewrite Makefile, remove EHAL

### PR DESCRIPTION
**Pull request by Informatic**
Fixed #48, added Version, AppSize and BootloaderAddress sections in linkerscript, fixed conflict.

### CODE REVIEW

**Comment by mariusheil** [comment]
Currently testing this on Windows. What would you say is the preferred way to set the SDK_PATH and SOFTDEVICE_PATH? probably set it in Makefile.local? I think I'd call it NRF5_SDK_PATH to avoid possible name clash.
- I have a problem with the mkdir command which seems to be a console built-in application on windows, this suggestion from stackoverflow seems to work however:
```
ifeq ($(OS),Windows_NT)
   MK = mkdir $(subst /,\,$@) > nul 2>&1 || (exit 0)
else
   MK = mkdir $@
endif
```
- Why did you call the resulting file .out instead of .hex? Any special reason?
- What is your intended usage of PROGFLAGS?
- We can add a flash target and rename the current one to flash_app. This target could flash Softdevice and app in one shot. I've noticed that this is usually faster and less error-prone instead of only flashing the app.

What do you think? :-)

**Comment by Informatic** [comment]
28.04.2016 10:26, Marius Heil wrote:
> Currently testing this on Windows. What would you say is the preferred way to 
> set the SDK_PATH and SOFTDEVICE_PATH? probably set it in Makefile.local? I think 
> I'd call it NRF5_SDK_PATH to avoid possible name clash.
I didn't make it clear - SOFTDEVICE_PATH is dependent on SDK_PATH and
set in Makefile.NRF51/NRF52. The point about name clash is fine (I
wanted to keep the variable names intact to begin with), I'll change
that to NRF5_SDK_PATH then.

>   * I have a problem with the mkdir command which seems to be a console built-in
>     application on windows, this suggestion from stackoverflow seems to work
>     however:
> 
> |ifeq ($(OS),Windows_NT) MK = mkdir $(subst /,\,$@) > nul 2>&1 || (exit 0) else 
> MK = mkdir $@ endif |
I'll patch that and add another commit to this PR today.

>   * Why did you call the resulting file .out instead of .hex? Any special reason?
There is .out (ELF file) and .hex built as well, same as before. Only
.bin building has been ommitted, since I didn't really see it used
anywhere anyway.

>   * What is your intended usage of PROGFLAGS?
I added `PROGFLAGS` personally for options such as `-s` to flash only
selected target (one can change these flags in make command, such as:
`make flash PROGFLAGS="-s 1234567"`, I rewrote your batch script for
mass flash for *nix-ish systems with dynamic detection of devices -
https://gist.github.com/6a625866239b62ad7e3d4b2300e8f0c0)

>   * We can add a flash target and rename the current one to flash_app. This
>     target could flash Softdevice and app in one shot. I've noticed that this is
>     usually faster and less error-prone instead of only flashing the app.
That's not a bad idea, I'll update that too then. (Didn't really stumble
upon such problems, only once when playing around with linkerscript, but
that's understandable :))

**Comment by Informatic** [comment]
> Currently testing this on Windows. What would you say is the preferred way to 
> set the SDK_PATH and SOFTDEVICE_PATH? probably set it in Makefile.local? I think 
> I'd call it NRF5_SDK_PATH to avoid possible name clash.

I didn't make it clear - SOFTDEVICE_PATH is dependent on SDK_PATH and
set in Makefile.NRF51/NRF52. The point about name clash is fine (I
wanted to keep the variable names intact to begin with), I'll change
that to NRF5_SDK_PATH then.

>   * I have a problem with the mkdir command which seems to be a console built-in
>     application on windows, this suggestion from stackoverflow seems to work
>     however:
> 
> |ifeq ($(OS),Windows_NT) MK = mkdir $(subst /,\,$@) > nul 2>&1 || (exit 0) else 
> MK = mkdir $@ endif |

I'll patch that and add another commit to this PR today.

>   * Why did you call the resulting file .out instead of .hex? Any special reason?
There is .out (ELF file) and .hex built as well, same as before. Only
.bin building has been ommitted, since I didn't really see it used
anywhere anyway.

>   * What is your intended usage of PROGFLAGS?

I added `PROGFLAGS` personally for options such as `-s` to flash only
selected target (one can change these flags in make command, such as:
`make flash PROGFLAGS="-s 1234567"`, I rewrote your batch script for
mass flash for *nix-ish systems with dynamic detection of devices -
https://gist.github.com/6a625866239b62ad7e3d4b2300e8f0c0)

>   * We can add a flash target and rename the current one to flash_app. This
>     target could flash Softdevice and app in one shot. I've noticed that this is
>     usually faster and less error-prone instead of only flashing the app.

That's not a bad idea, I'll update that too then. (Didn't really stumble
upon such problems, only once when playing around with linkerscript, but
that's understandable :))

PS. Crap. I broke the GH markdown

**Comment by mariusheil** [comment]
Nice :-) I really appreciate the help. Seems like I've overlooked the SOFTDEVICE_PATH. I tested everything in Eclipse and it works just fine. I'll update my fruitymesh-devenv with the makefile approach and will use that myself from now on, seemed to work quite good.

**Comment by Informatic** [comment]
I've force-pushed mentioned fixes.

**Comment by Informatic** [comment]
Oh. I've had to force-push these again, since I happened to break dependency building. Sorry. ;)

**Comment by mariusheil** [comment]
That's alright. If you want you can delete the --sector-erase for the flash target because that's not needed after a chiperase.

**Comment by Informatic** [comment]
That's correct, forgot about that. Done.

**Comment by mariusheil** [comment]
One more thing :-) Could you please add one line to the nrf5x_common.ld? It's the application start address that I need for my bootloader:
```
	{		
 		__application_start_address = .;
		KEEP(*(.isr_vector))

		KEEP(*(.Version))
		KEEP(*(.AppSize))
```
I'll have to run some tests if everything will still work with my bootloader and then i will merge this request.

**Comment by Informatic** [comment]
Yes, I've screwed the incremental builds up, and then force pushed the fix. It should work now on 1e4ab8d

**Comment by mariusheil** [comment]
looks good in my tests :-) incmremental build and everything working, I am currently finalizing everything and will push the changes

**Comment by Informatic** [comment]
It seems it has already been merged in latest commits, closing.

**Pull request closed without merging**
